# Full CI flow for the project
name: Continuous Integration

on:
  # master branch will not accept if any failed
  # staging branch will accept regardless of the status of the jobs
  pull_request:
    branches:
      - development
      - staging
      - main
  push:
    branches:
      - development
      - staging
      - main
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20.16.0

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm@9.7

      # Cache Node.js dependencies
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            cache-node-modules-

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Run Prettier
      - name: Run Prettier
        run: pnpm format:check

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20.16.0

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm@9.7

      # Cache Node.js dependencies
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            cache-node-modules-

      # Install dependencies
      - name: Install dependencies
        run: pnpm install:ci

      # Run Typecheck
      - name: Run Typecheck
        run: pnpm typecheck

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20.16.0

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm@9.7

      # Cache Node.js dependencies
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            cache-node-modules-

      # Install dependencies
      - name: Install dependencies
        run: pnpm install:ci

      # Build (required for ESLint to import the plugin)
      - name: Build
        run: pnpm build

      # Run ESLint
      - name: Run ESLint
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    needs: [format, typecheck, lint]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20.16.0

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm@9.7

      # Cache Node.js dependencies
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            cache-node-modules-

      # Install dependencies
      - name: Install dependencies
        run: pnpm install:ci

        # Run the test suite
      - name: Run tests
        run: pnpm test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20.16.0

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm@9.7

      # Cache Node.js dependencies
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            cache-node-modules-

      # Install dependencies
      - name: Install dependencies
        run: pnpm install:ci

      # Run build
      - name: Run build
        run: pnpm build
